services:
  entrenar:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/battery_RUL_with_ID.csv:/data/inputs/battery_RUL_with_ID.csv:ro
      - ./model:/data/outputs
      - ./variables.json:/data/config/variables.json:ro
