apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo
data:
  default-v1: |
    archiveLogs: true
    s3:
      endpoint: minio.minio-dev.svc:9000
      bucket: argo-artifacts
      insecure: true
      accessKeySecret:
        name: minio-creds
        key: accessKey
      secretKeySecret:
        name: minio-creds
        key: secretKey
