
services:
  generar:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./modelo:/data/inputs
      - ./variables.json:/data/config/variables.json:ro
      - ./datos_sinteticos:/data/outputs
