services:
  generar:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./model:/data/inputs
      - ./variables.json:/data/config/variables.json:ro
      - ./data_synth:/data/outputs
